# Generated by Django 5.1.7 on 2025-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
